remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: false
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project.

title: "Sip & Score"
description: "Find your next favorite cocktail and bar"
author:
  name: "Russell Brazell"

# Do not change the following line.
  copyright: true
